{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "Data Engineer Challenge.ipynb",
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 1000
        },
        "id": "4Ot6fC3kRpuA",
        "outputId": "1cf99773-6291-4dcc-a63b-7e41d4ea15c5"
      },
      "source": [
        "import sys\n",
        "sys.setrecursionlimit(5000)\n",
        "\n",
        "#import library yang dibutuhkan\n",
        "import pandas as pd\n",
        "import requests\n",
        "from bs4 import BeautifulSoup\n",
        "\n",
        "#buatlah request ke website\n",
        "website_url = requests.get('https://id.wikipedia.org/wiki/Demografi_Indonesia').text\n",
        "soup = BeautifulSoup(website_url, 'lxml')\n",
        "\n",
        "#ambil table dengan class 'wikitable sortable'\n",
        "my_table = soup.find('table', {'class':'wikitable sortable'})\n",
        "\n",
        "#cari data dengan tag 'td'\n",
        "links = my_table.findAll('td')\n",
        "\n",
        "#buatlah lists kosong \n",
        "nama = []\n",
        "luas_km = []\n",
        "populasi10 = []\n",
        "populasi20 = []\n",
        "\n",
        "#memasukkan data ke dalam list berdasarkan pola HTML\n",
        "for i, link in enumerate(links):\n",
        "\tif i in range(0, len(links), 4):\n",
        "\t\tnama.append(link.get_text())\n",
        "\tif i in range(1, len(links), 4):\n",
        "\t\tluas_km.append(link.get_text())\n",
        "\tif i in range(2, len(links), 4):\n",
        "\t\tpopulasi10.append(link.get_text())\n",
        "\tif i in range(3, len(links), 4):\n",
        "\t\tpopulasi20.append(link.get_text()[:-1])\n",
        "\n",
        "#buatlah DataFrame dan masukkan ke CSV\n",
        "df = pd.DataFrame()\n",
        "df['Nama Provinsi'] = nama\n",
        "df['Luas km'] = luas_km\n",
        "df['Populasi 2010'] = populasi10\n",
        "df['Populasi 2020'] = populasi20\n",
        "df.to_csv('Indonesia_Demography_by_Province.csv', index=False, encoding='utf-8', quoting=1)\n",
        "df"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/html": [
              "<div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>Nama Provinsi</th>\n",
              "      <th>Luas km</th>\n",
              "      <th>Populasi 2010</th>\n",
              "      <th>Populasi 2020</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>Aceh\\n</td>\n",
              "      <td>56.500,51\\n</td>\n",
              "      <td>4.494.410\\n</td>\n",
              "      <td>5.274.871</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>Sumatra Utara\\n</td>\n",
              "      <td>72.427,81\\n</td>\n",
              "      <td>12.982.204\\n</td>\n",
              "      <td>14.799.361</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>Sumatra Barat\\n</td>\n",
              "      <td>42.224,65\\n</td>\n",
              "      <td>4.846.909\\n</td>\n",
              "      <td>5.534.472</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>Riau\\n</td>\n",
              "      <td>87.844,23\\n</td>\n",
              "      <td>5.538.367\\n</td>\n",
              "      <td>6.394.087</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>Jambi\\n</td>\n",
              "      <td>45.348,49\\n</td>\n",
              "      <td>3.092.265\\n</td>\n",
              "      <td>3.548.228</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>5</th>\n",
              "      <td>Sumatra Selatan\\n</td>\n",
              "      <td>60.302,54\\n</td>\n",
              "      <td>7.450.394\\n</td>\n",
              "      <td>8.467.432</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>6</th>\n",
              "      <td>Bengkulu\\n</td>\n",
              "      <td>19.795,15\\n</td>\n",
              "      <td>1.715.518\\n</td>\n",
              "      <td>2.010.670</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>7</th>\n",
              "      <td>Lampung\\n</td>\n",
              "      <td>37.735,15\\n</td>\n",
              "      <td>7.608.405\\n</td>\n",
              "      <td>9.007.848</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>8</th>\n",
              "      <td>Kepulauan Bangka Belitung\\n</td>\n",
              "      <td>16.424,14\\n</td>\n",
              "      <td>1.223.296\\n</td>\n",
              "      <td>1.455.678</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>9</th>\n",
              "      <td>Kepulauan Riau\\n</td>\n",
              "      <td>8.084,01\\n</td>\n",
              "      <td>1.679.163\\n</td>\n",
              "      <td>2.064.564</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>10</th>\n",
              "      <td>Daerah Khusus Ibukota Jakarta\\n</td>\n",
              "      <td>740,29\\n</td>\n",
              "      <td>9.607.787\\n</td>\n",
              "      <td>10.562.088</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>11</th>\n",
              "      <td>Jawa Barat\\n</td>\n",
              "      <td>36.925,05\\n</td>\n",
              "      <td>43.053.732\\n</td>\n",
              "      <td>48.274.162</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>12</th>\n",
              "      <td>Jawa Tengah\\n</td>\n",
              "      <td>32.799,71\\n</td>\n",
              "      <td>32.382.657\\n</td>\n",
              "      <td>36.516.035</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>13</th>\n",
              "      <td>Daerah Istimewa Yogyakarta\\n</td>\n",
              "      <td>3.133,15\\n</td>\n",
              "      <td>3.457.491\\n</td>\n",
              "      <td>3.668.719</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>14</th>\n",
              "      <td>Jawa Timur\\n</td>\n",
              "      <td>46.689,64\\n</td>\n",
              "      <td>37.476.757\\n</td>\n",
              "      <td>40.665.696</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>15</th>\n",
              "      <td>Banten\\n</td>\n",
              "      <td>9.018,64\\n</td>\n",
              "      <td>10.632.166\\n</td>\n",
              "      <td>11.904.562</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>16</th>\n",
              "      <td>Bali\\n</td>\n",
              "      <td>5.449,37\\n</td>\n",
              "      <td>3.890.757\\n</td>\n",
              "      <td>4.317.404</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>17</th>\n",
              "      <td>Nusa Tenggara Barat\\n</td>\n",
              "      <td>19.708,79\\n</td>\n",
              "      <td>4.500.212\\n</td>\n",
              "      <td>5.320.092</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>18</th>\n",
              "      <td>Nusa Tenggara Timur\\n</td>\n",
              "      <td>46.137,87\\n</td>\n",
              "      <td>4.683.827\\n</td>\n",
              "      <td>5.325.566</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>19</th>\n",
              "      <td>Kalimantan Barat\\n</td>\n",
              "      <td>120.114,32\\n</td>\n",
              "      <td>4.395.983\\n</td>\n",
              "      <td>5.414.390</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>20</th>\n",
              "      <td>Kalimantan Tengah\\n</td>\n",
              "      <td>153.564,50\\n</td>\n",
              "      <td>2.212.089\\n</td>\n",
              "      <td>2.669.969</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>21</th>\n",
              "      <td>Kalimantan Selatan\\n</td>\n",
              "      <td>37.530,52\\n</td>\n",
              "      <td>3.626.616\\n</td>\n",
              "      <td>4.073.584</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>22</th>\n",
              "      <td>Kalimantan Timur\\n</td>\n",
              "      <td>194.849,08\\n</td>\n",
              "      <td>3.553.143\\n</td>\n",
              "      <td>3.766.039</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>23</th>\n",
              "      <td>Kalimantan Utara\\n</td>\n",
              "      <td>72.567,49\\n</td>\n",
              "      <td>738.163\\n</td>\n",
              "      <td>701.814</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>24</th>\n",
              "      <td>Sulawesi Utara\\n</td>\n",
              "      <td>13.930,73\\n</td>\n",
              "      <td>2.270.596\\n</td>\n",
              "      <td>2.621.923</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>25</th>\n",
              "      <td>Sulawesi Tengah\\n</td>\n",
              "      <td>68.089,83\\n</td>\n",
              "      <td>2.635.009\\n</td>\n",
              "      <td>2.985.734</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>26</th>\n",
              "      <td>Sulawesi Selatan\\n</td>\n",
              "      <td>46.116,45\\n</td>\n",
              "      <td>8.034.776\\n</td>\n",
              "      <td>9.073.509</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>27</th>\n",
              "      <td>Sulawesi Tenggara\\n</td>\n",
              "      <td>36.757,45\\n</td>\n",
              "      <td>2.232.586\\n</td>\n",
              "      <td>2.624.875</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>28</th>\n",
              "      <td>Gorontalo\\n</td>\n",
              "      <td>12.165,44\\n</td>\n",
              "      <td>1.040.164\\n</td>\n",
              "      <td>1.171.681</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>29</th>\n",
              "      <td>Sulawesi Barat\\n</td>\n",
              "      <td>16.787,19\\n</td>\n",
              "      <td>1.158.651\\n</td>\n",
              "      <td>1.419.229</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>30</th>\n",
              "      <td>Maluku\\n</td>\n",
              "      <td>47.350,42\\n</td>\n",
              "      <td>1.533.506\\n</td>\n",
              "      <td>1.848.923</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>31</th>\n",
              "      <td>Maluku Utara\\n</td>\n",
              "      <td>39.959,99\\n</td>\n",
              "      <td>1.038.087\\n</td>\n",
              "      <td>1.282.937</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>32</th>\n",
              "      <td>Papua Barat\\n</td>\n",
              "      <td>114.566,40\\n</td>\n",
              "      <td>760.422\\n</td>\n",
              "      <td>1.134.068</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>33</th>\n",
              "      <td>Papua\\n</td>\n",
              "      <td>309.934,40\\n</td>\n",
              "      <td>2.833.381\\n</td>\n",
              "      <td>4.303.707</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>"
            ],
            "text/plain": [
              "                      Nama Provinsi       Luas km Populasi 2010 Populasi 2020\n",
              "0                            Aceh\\n   56.500,51\\n   4.494.410\\n     5.274.871\n",
              "1                   Sumatra Utara\\n   72.427,81\\n  12.982.204\\n    14.799.361\n",
              "2                   Sumatra Barat\\n   42.224,65\\n   4.846.909\\n     5.534.472\n",
              "3                            Riau\\n   87.844,23\\n   5.538.367\\n     6.394.087\n",
              "4                           Jambi\\n   45.348,49\\n   3.092.265\\n     3.548.228\n",
              "5                 Sumatra Selatan\\n   60.302,54\\n   7.450.394\\n     8.467.432\n",
              "6                        Bengkulu\\n   19.795,15\\n   1.715.518\\n     2.010.670\n",
              "7                         Lampung\\n   37.735,15\\n   7.608.405\\n     9.007.848\n",
              "8       Kepulauan Bangka Belitung\\n   16.424,14\\n   1.223.296\\n     1.455.678\n",
              "9                  Kepulauan Riau\\n    8.084,01\\n   1.679.163\\n     2.064.564\n",
              "10  Daerah Khusus Ibukota Jakarta\\n      740,29\\n   9.607.787\\n    10.562.088\n",
              "11                     Jawa Barat\\n   36.925,05\\n  43.053.732\\n    48.274.162\n",
              "12                    Jawa Tengah\\n   32.799,71\\n  32.382.657\\n    36.516.035\n",
              "13     Daerah Istimewa Yogyakarta\\n    3.133,15\\n   3.457.491\\n     3.668.719\n",
              "14                     Jawa Timur\\n   46.689,64\\n  37.476.757\\n    40.665.696\n",
              "15                         Banten\\n    9.018,64\\n  10.632.166\\n    11.904.562\n",
              "16                           Bali\\n    5.449,37\\n   3.890.757\\n     4.317.404\n",
              "17            Nusa Tenggara Barat\\n   19.708,79\\n   4.500.212\\n     5.320.092\n",
              "18            Nusa Tenggara Timur\\n   46.137,87\\n   4.683.827\\n     5.325.566\n",
              "19               Kalimantan Barat\\n  120.114,32\\n   4.395.983\\n     5.414.390\n",
              "20              Kalimantan Tengah\\n  153.564,50\\n   2.212.089\\n     2.669.969\n",
              "21             Kalimantan Selatan\\n   37.530,52\\n   3.626.616\\n     4.073.584\n",
              "22               Kalimantan Timur\\n  194.849,08\\n   3.553.143\\n     3.766.039\n",
              "23               Kalimantan Utara\\n   72.567,49\\n     738.163\\n       701.814\n",
              "24                 Sulawesi Utara\\n   13.930,73\\n   2.270.596\\n     2.621.923\n",
              "25                Sulawesi Tengah\\n   68.089,83\\n   2.635.009\\n     2.985.734\n",
              "26               Sulawesi Selatan\\n   46.116,45\\n   8.034.776\\n     9.073.509\n",
              "27              Sulawesi Tenggara\\n   36.757,45\\n   2.232.586\\n     2.624.875\n",
              "28                      Gorontalo\\n   12.165,44\\n   1.040.164\\n     1.171.681\n",
              "29                 Sulawesi Barat\\n   16.787,19\\n   1.158.651\\n     1.419.229\n",
              "30                         Maluku\\n   47.350,42\\n   1.533.506\\n     1.848.923\n",
              "31                   Maluku Utara\\n   39.959,99\\n   1.038.087\\n     1.282.937\n",
              "32                    Papua Barat\\n  114.566,40\\n     760.422\\n     1.134.068\n",
              "33                          Papua\\n  309.934,40\\n   2.833.381\\n     4.303.707"
            ]
          },
          "metadata": {
            "tags": []
          },
          "execution_count": 16
        }
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "DTIx_B50Yx-Y"
      },
      "source": [
        "## Fuction and Regular Expression"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "Fm3LIAHaRvW4",
        "outputId": "08b9c424-2e81-4fe3-ab04-932cc9c4bb78"
      },
      "source": [
        "#import library yang dibutuhkan\n",
        "import re\n",
        "#function email_check\n",
        "def email_check(input):\n",
        "  match = re.search('(?=^((?!-).)*$)(?=[0-9])((?=^((?!\\.\\d).)*$)|(?=.*_))',input)\n",
        "  if match:\n",
        "    print('Pass')\n",
        "  else:\n",
        "    print('Not Pass')\n",
        "#Masukkan data email ke dalam list\n",
        "emails = ['my-name@someemail.com', 'myname@someemail.com', 'my.name@someemail.com',\n",
        "'my.name2019@someemail.com', 'my.name.2019@someemail.com',\n",
        "'somename.201903@someemail.com','my_name.201903@someemail.com',\n",
        "'201903myname@someemail.com', '201903.myname@someemail.com']\n",
        "#Looping untuk pengecekan Pass atau Not Pass\n",
        "for email in emails :\n",
        "  email_check(email)"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "Not Pass\n",
            "Not Pass\n",
            "Not Pass\n",
            "Not Pass\n",
            "Not Pass\n",
            "Not Pass\n",
            "Not Pass\n",
            "Pass\n",
            "Pass\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "pzJIyZREY1Q3",
        "outputId": "459fd866-2467-45d9-ced7-55b53d23615f"
      },
      "source": [
        "dic1={1:10, 2:20}\n",
        "dic2={3:30, 4:40}\n",
        "dic3={5:50,6:60}\n",
        "dic4 = {}\n",
        "for d in (dic1, dic2, dic3):\n",
        "\tdic4.update(d)\n",
        "print(dic4)"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "{1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60}\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 129
        },
        "id": "QFAr6pXObNyL",
        "outputId": "3cf7d07d-3431-4bba-aed5-f8c5d5beb36e"
      },
      "source": [
        "# Buat fungsi penjumlahan deret Fibonacci\n",
        "def calculateSum(n):\n",
        "\tif n <= 0 :\n",
        "    \treturn n;\n",
        "    fibo = [0] * n\n",
        "    fibo[1] = 1\n",
        "    # Initialisasi hasil ke dalam variabel sm\n",
        "    sm = fibo + fibo[1]\n",
        "    # Tambahkan suku-suku berikutnya\n",
        "    for i in n+1:\n",
        "    \tfibo[i] = fibo[i-1] + fibo[i-2]\n",
        "        sm += fibo[i];\n",
        "    return sm\n",
        "# Evaluasi hasil deret untuk n = 7    \n",
        "print( calculateSum(7))"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "error",
          "ename": "TabError",
          "evalue": "ignored",
          "traceback": [
            "\u001b[0;36m  File \u001b[0;32m\"<ipython-input-28-b36fbbdebfdb>\"\u001b[0;36m, line \u001b[0;32m4\u001b[0m\n\u001b[0;31m    return n;\u001b[0m\n\u001b[0m             ^\u001b[0m\n\u001b[0;31mTabError\u001b[0m\u001b[0;31m:\u001b[0m inconsistent use of tabs and spaces in indentation\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "Fn020KHHe18M"
      },
      "source": [
        ""
      ],
      "execution_count": null,
      "outputs": []
    }
  ]
}